[package]
name = "paradoxmerger"
version = "0.1.0"
authors = ["Parker Okonek <parkerokonek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unidiff = "0.3"
toml = "0.5"
zip = "0.5"
clap = "2"
serde = {version = "1.0", features = ["derive"]}
regex = "1"
pyo3 = "0.9"