name: BuildGUI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Deps
      run: sudo apt install lib-gtk3.0
    - name: Build
      run: cargo build --features gtk-interface --bin merger-gui --verbose
